"""Add soft delete columns to papers table

Revision ID: 042d3cce9a33
Revises: 669b2de1fcd7
Create Date: 2026-05-31 21:58:30.495517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042d3cce9a33'
down_revision = '669b2de1fcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_papers_deleted_by_user_id_users', 'users', ['deleted_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_papers_deleted_by_user_id_users', type_='foreignkey')
        batch_op.drop_column('deleted_by_user_id')
        batch_op.drop_column('deleted_at')
    # ### end Alembic commands ###
