"""Initial schema

Revision ID: 669b2de1fcd7
Revises: 
Create Date: 2026-05-29 02:08:49.822659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669b2de1fcd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_license_status'), ['license_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_license_type'), ['license_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_public_id'))
        batch_op.drop_index(batch_op.f('ix_models_license_type'))
        batch_op.drop_index(batch_op.f('ix_models_license_status'))

    # ### end Alembic commands ###
